# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "/"
languageCode = "en-AU"
title = "Notasi - Data Centralisation and Analytics for Schools and SMBs"

# Metadata
[params]
  author = "Tully Clark"
  description = "Notasi focuses on data centralisation, so you can focus on insights. Notasi simplifies the data analytics process for your school or small business."

# Hero section (from here on is for icon theme)
[params.hero]
  title = "Notasi<sup class='beta'> BETA</sup>"
  subtitle = "...all your data <span id=subtitle-1>Stored</span><span id=subtitle-2>Scheduled</span><span id=subtitle-3>Queried</span><span id=subtitle-4>Connected</span><span id=subtitle-5>Visualised</span><br>...all without a DBA"
  description = "[Download Now](https://github.com/tullyclark/notasi)"

# Navigation section
[params.nav]
  mission = "Features"
  services = "Screenshots"
  uses = "Use Cases"
  contact = "Contact"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true
  heading = "What Can Notasi Do"

  [[params.mission.item]]
    weight = 1
    name = "store"
    title = "Store"
    subtitle = "No DBA Needed!"    
    description = "<p>Don't worry about data types, complex database architecture or time consuming ETL processes. Just enter the connection details, the query options, and what values make the information unique and Notasi handles the rest. It even stores a full history of all changes made to the data.<br><br>Once you've got your data, schedule with familiar and powerful CRON scheduling.</p><ul class='checked'><li>SQL</li><li>HTTP APIs</li><li>CSV/JSON</li><li>LDAP</li></ul>"

  [[params.mission.item]]
    weight = 2
    name = "query"
    title = "Query"
    subtitle = "All your data in one place!"
    description = "<p>Combine your data sources effortlessly, all you need is a little bit of SQL. Database views are automatically generated, so querying your data is as simple as can be!</p><ul class='checked'><li>Direct database connection</li><li>Custom REST APIs</li></ul>"

  [[params.mission.item]]
    weight = 3
    name = "connect"
    title = "Connect"
    subtitle = "No more waiting for underpowered 1<sup>st</sup> party connectors"
    description = "<p>Don't wait for your \"favourite\" software company to develop the connectors you need, do it yourself without the stress of custom development. Use the data stored in Notasi as variables in API calls and SQL queries</p>"

  [[params.mission.item]]
    weight = 4
    name = "visualise"
    title = "Visualise"
    subtitle = "New Dashboards in Seconds!"
    description = "<p>Build mobile ready dashboards and embed them in record time. Notasi handles the layout, pagination and permissions so you can focus on communicating insights to your users!</p><ul class='checked'><li>Responsive Layout</li><li>Automatic Pagination</li><li>As simple or as complex as you need</li><li>Row level security</li><li>Expand built in capabilities (Chart.js)</li></ul>"

# Services section
[params.services]
  enable = true
  video = false
  title = "See Notasi"

  [[params.services.item]]
    title = "Processes"
    subtitle = "See all data sources from 1 screen"
    img = "images/process.png"

  [[params.services.item]]
    title = "Schedule"
    subtitle = "Flexible CRON scheduling"
    img = "images/schedule.png"

  [[params.services.item]]
    title = "Groups"
    subtitle = "Easy group management"
    img = "images/groups.png"

  [[params.services.item]]
    title = "Endpoints"
    subtitle = "Custom REST endpoints"
    img = "images/endpoint.png"

  [[params.services.item]]
    title = "Query"
    subtitle = "Make API calls with variables"
    img = "images/api_query.png"

  [[params.services.item]]
    title = "Chart Configuration"
    subtitle = "Simple Chart Configuration"
    img = "images/chart_config.png"

  [[params.services.item]]
    title = "Charts and Dashboards"
    subtitle = "Responsive, Paginated, iFrame-able"
    img = "images/chart.png"

# Uses section
[params.uses]
  enable = true
  heading = "Use Notasi for"

  [[params.uses.item]]
    weight = 1
    name = "spreadsheet"
    title = "Handling Spreadsheets"
    subtitle = "Run SQL on your spreadsheets!"
    description = "<p>Spreadsheets still have an incredibly important role in most businesses, but unless you want to hire a VBA developer, using this data is clumsy and manual. Notasi lets you build SQL views from spreadsheets without stressing over schema particulars, and you get to see a full history of the information stored. If you're looking for a more resilient, reliant way of running analytics on your data, Notasi is your perfect solution.</p>"

  [[params.uses.item]]
    weight = 2
    name = "api"
    title = "Custom Database API"
    subtitle = "Build powerful APIs with a little bit of SQL!"
    description = "<p>If you have security concerns about opening up your database to third party applications, Notasi has a quick and clean solution. You can build custom REST API's that only access the data you want it to. Just enter a SQL query, and then any column returned is available as a variable to include in your request body or as URL parameters.</p>"

  [[params.uses.item]]
    weight = 3
    name = "pot"
    title = "Point in Time Lookup"
    subtitle = "See what your data looked like at any point in time!"
    description = "<p>Notasi is really clever in the way it stores your data. Every time you write data into Notasi, it checks what information has changes since the last write. It timestamps all the data and lets you know whether a certain piece of information came through in the last write.</p>"


  [[params.uses.item]]
    weight = 4
    name = "middleware"
    title = "LMS Syncing"
    #subtitle = "Replace your custom code!"
    description = '''<p>Replacing your custom, hard to maintain scripts is easy with Notasi. But how does it work?
    <br>
    <br>
    First you need to get all your data out of your SIS. Notasi doesn't mind which system the information is coming from, and you can access it over REST APIs, SQL Queries or even CSV or JSON files. You can pull in all your users, their classes and even the assessments from the SIS.
    <br>
    <br>
    Next you'll need to get the newly stored data from Notasi and into your LMS. With most systems, you can do that with their REST API, so set up a new connection with the URL for the LMS. Then, create a new query:
    </p>
    <ol>
      <li>Enter the query's name and associated location</li>
      <li>Enter a SQL Query to get the data from Notasi</li>
      <li>Choose an endpoint and request type</li>
      <li>Finally, enter a header and body for the request. You can use {curly brackets} around column names from the data lake query to include variables. It will make one request per row returned by the data lake query</li>
    </ol
    <p>
    You'll need to repeat steps 1-4 for every type of data you want to sync (e.g. students, classes, assessments), depending on how your LMS uses the provided information.
    <br>
    <br>
    Retrieving assessment results is just as easy, just set up the queries and store the information with views.
    </p>'''

  [[params.uses.item]]
    weight = 5
    name = "dashboard"
    title = "User Focused Dashboards"
    subtitle = "Personal dashboards for all your users!"
    description = "<p>Once you've got some data in Notasi, you might want to set up dashboards</p>"


# Contact section
[params.contact]
  enable = true
  title = "Want to Use Notasi? Get In Touch"
  #message = "Got Questions?"
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p> Notasi is built by Tully Clark and released under the Apache License<br><small>Website design &copy; 2016 Free HTML5 Template. All Rights Reserved."
#  github = "https://github.com/tullyclark/notasi"
#  twitter = "#"
#  facebook = "#"
#  vine = "#"
#  linkedin = "#"
#  instagram = "#"
  